### ISSUE TITLE
possible story conflict

### ISSUE THREAD

**Issue by Roars-Tech** [andreicruceru95/App06-Group#14]
having shops and blacksmiths past the town area, doesn't seem plausible, can we discuss this. 
A couple of idea's; 
1) the user has to go back to town to upgrade and restock supplies, although realistic, it can get tedious for the player to go back to town every time, especially if they're through the teleporter
2) some form of remote upgrade that the player can do themselves? maybe they have to be in a "safe" location ie no monsters on screen or designated rocky coves  or caves on the map?

**Comment by andreicruceru95** [comment]
The shop and blacksmith in the other maps are added for testing purposes.

Two possible ideas i thought of are

1. adding a quick teleport function where every newly discovered map is
added.

2. Adding a small 'town' in each map that would contain the shop and
blacksmith and might benefit for possible quests

**Comment by andreicruceru95** [comment]
I do like the remote upgrade idea, it would be great to add

**Comment by Roars-Tech** [comment]
okay, so you can implement cave or rocks in a 3x3 (or 4x4), with a side left open on the maps that contains an anvil?
xxxx
x a x
x    x

we can then work in a quest on the first level / map to obtain a hammer from the blacksmith. something like upgrade each piece of equipment once? the blacksmith could then say something like, here take this hammer so you can upgrade your own items on the journey. we also have to think about cost of remote upgrade, maybe put a "toll" to enter the cave or if possible have the monsters drop "crafting materials" however this would decrease gold usage to just potions. 

Having a settlement of adventurers in each map could help, but I'd say there shouldn't be one on the final map.

I can work either or into the story, it's what ever you feel comfortable with programming.

**Comment by andreicruceru95** [comment]
Yes this would work well

**Comment by Roars-Tech** [comment]
which one :) you choose and I'll adjust the story accordingly

**Comment by andreicruceru95** [comment]
The anvil will be easy and effective. We need to think about the location of it as well.

**Comment by Roars-Tech** [comment]
okay, I'll adjust the story, what are you going to do regarding the cost of upgrades and gold?
are you happy to implement material drops to monsters for the upgrade cost? if so I'll have a think on a way we can use gold so its not just for potions.

**Comment by andreicruceru95** [comment]
if we add material drop, we could add that to the shop as an option to buy?

**Comment by andreicruceru95** [comment]
I have added anvil throughout the maps where the player can upgrade its  items.

Each upgrade requires $ only for now.
