### ISSUE TITLE
We need a lot of battle testing to find the right player stats / monster stats balance

### ISSUE THREAD

**Issue by andreicruceru95** [andreicruceru95/App06-Group#15]

**Comment by Roars-Tech** [comment]
that will be okay, are you able to create a temporary teleporter near spawn that will send you to a map with rows of monsters, with a black smith & shop? this will make testing easier and faster :)  E.G.

(with a couple of spaces between each monster left to right, but no need for spaces below.
---------------------------------------------------------------------------------------
Shop                                player                                       blacksmith


1          2           3            etc....
1          2           3
1          2           3
1          2           3
1          2           3
1          2           3
1          2           3
1          2           3
1          2           3
1          2           3

**Comment by andreicruceru95** [comment]
Okay, that's a great idea.

I will add a test map that contains shop& blacksmith and all the monsters.

Might take too long to add them on columns but i will try. If not, I will
create a standard size map

**Comment by Roars-Tech** [comment]
that's okay, let me know when done and I'll test it

**Comment by andreicruceru95** [comment]
Added the test map. You can also go back into town from the test map if you want
