### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Roars-Tech** [andreicruceru95/App06-Group#19]
Possibility of adding an item, such as a teleport crystal, obtained from a quest or boss drop that will teleport you to the town on that map? (would this be possible?) if not I thought of having it send you to the starting town however, the walk back would be tedious if used a few levels deep, although would make completing the game when obtained the mythical stone easier and less tedious than walking all the way back, although, it could be part of the game that you have to make it back alive anyway?

**Comment by andreicruceru95** [comment]
Yes we can make this happen. Using the teleport crystal could show all the discovered maps including the town map, so the player can quickly travel to town and back to the map

**Comment by andreicruceru95** [comment]
Function is in working order
