### ISSUE TITLE
Nice idea to have recurring movement?

### ISSUE THREAD

**Issue by Warrenboy1** [andreicruceru95/App06-Group#23]
like an example since players may want to move to different areas of the map/game quickly, they will definitely get impatient with pressing either W,A,S,D keys ONCE and then enter to move.   we can implement a function so when they accidentally press the key multiple times...the player will still move in that direction...

basically i am supporting the function to quickly move around rather then getting the player to be patient with how the movement system works.

**Comment by andreicruceru95** [comment]
I can implement that

**Comment by andreicruceru95** [comment]
I added this, Have a look.
